# Generated by Django 4.2 on 2024-01-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
